// Generated by https://quicktype.io

export interface ProductResponse {
  id: number
  title: string
  price: number
  description: string
  category: Category
  image: string
  rating: Rating
}

export interface Product {
  id: number
  title: string
  price: number
  description: string
  category: Category
  image: string
  rating: number
  isPrime: boolean
}

export interface CheckoutProduct extends Product {
  checkProductId: string
}

export enum Category {
  Electronics = 'electronics',
  Jewelery = 'jewelery',
  MenSClothing = "men's clothing",
  WomenSClothing = "women's clothing",
}

export interface Rating {
  rate: number
  count: number
}

export interface User {
  uid: string
  name: string
  email: string
}

export interface DataBaseOrder {
  id: string
  amount: number
  amountShipping: number
  images: string[]
  timestamp: number
}

// Generated by https://quicktype.io

export interface OrderUser {
  id: string
  amount: number
  amountShipping: number
  images: string[]
  timestamp: number
  items: Item[]
}

interface Item {
  id: string
  object: string
  amount_discount: number
  amount_subtotal: number
  amount_tax: number
  amount_total: number
  currency: string
  description: string
  price: Price
  quantity: number
}

interface Price {
  id: string
  object: string
  active: boolean
  billing_scheme: string
  created: number
  currency: string
  custom_unit_amount: null
  livemode: boolean
  lookup_key: null
  metadata: Metadata
  nickname: null
  product: string
  recurring: null
  tax_behavior: string
  tiers_mode: null
  transform_quantity: null
  type: string
  unit_amount: number
  unit_amount_decimal: string
}
